export const ACTION_WORKSPACE_RUN = 'ACTION_WORKSPACE_RUN';
export const ACTION_WORKSPACE_STOP = 'ACTION_WORKSPACE_STOP';
export const ACTION_WORKSPACE_CREATE = 'ACTION_WORKSPACE_CREATE';
export const ACTION_WORKSPACE_REMOVE = 'ACTION_WORKSPACE_REMVOE';
export const ACTION_ASSIGN_USER = 'ACTION_ASSIGN_USER';

export const WORKSPACE_RUN = 'WORKSPACE_RUN';
export const WORKSPACE_STOP = 'WORKSPACE_STOP';
export const WORKSPACE_CREATE = 'WORKSPACE_CREATE';
export const WORKSPACE_REMOVE = 'WORKSPACE_REMOVE';


export const ASSIGN_USER = 'ASSIGN_USER';
export const REGISTER_KEY = 'REGISTER_KEY';

export const SET_WORKSPACE_STATUS = 'SET_WORKSPACE_STATUS';

export const STATUS_ACTIVE = 'STATUS_ACTIVE';
export const STATUS_SHUTDOWN = 'STATUS_SHUTDOWN';

export const REGISTER_SERVER = 'REGISTER_SERVER';

// Server status
export const STATUS_DISCONNECTED = 'STATUS_DISCONNECTED';
export const STATUS_CONNECTED = 'STATUS_CONNECTED';