
/** Deprecated */
export const JOB_STATUS_IN_PROGRESS = 'JOB_STATUS_IN_PROGRESS';
export const JOB_STATUS_DONE = 'JOB_STATUS_DONE';
export const JOB_STATUS_REJECTED = 'JOB_STATUS_REJECTED';

export const ACTION_JOB_START = 'ACTION_JOB_START';
export const ACTION_JOB_SET_STATUS = 'ACTION_JOB_SET_STATUS';

export const ACTION_JOB_MODIFY = 'ACTION_JOB_MODIFY';
/** Deprecated end */

export const WORKSPACE_STATUS_ACTIVE = 'STATUS_ACTIVE';
export const WORKSPACE_STATUS_SHUTDOWN = 'STATUS_SHUTDOWN';


export const ACTION_SELECT_WORKSPACE = 'ACTION_SELECT_WORKSPACE';
export const ACTION_WORKSPACES_METEOR_SYNC = 'ACTION_WORKSPACES_METEOR_SYNC';