
/** Deprecated */
export const JOB_STATUS_IN_PROGRESS = 'JOB_STATUS_IN_PROGRESS';
export const JOB_STATUS_DONE = 'JOB_STATUS_DONE';
export const JOB_STATUS_REJECTED = 'JOB_STATUS_REJECTED';

export const ACTION_JOB_START = 'ACTION_JOB_START';
export const ACTION_JOB_SET_STATUS = 'ACTION_JOB_SET_STATUS';

export const ACTION_JOB_MODIFY = 'ACTION_JOB_MODIFY';
/** Deprecated end */

export const WORKSPACE_STATUS_ACTIVE = 'STATUS_ACTIVE';
export const WORKSPACE_STATUS_SHUTDOWN = 'STATUS_SHUTDOWN';
export const WORKSPACE_STATUS_PROGRESS = 'STATUS_PROCESS';


export const ACTION_SELECT_WORKSPACE = 'ACTION_SELECT_WORKSPACE';
export const ACTION_DELETE_WORKSPACE = 'ACTION_DELETE_WORKSPACE';
export const ACTION_WORKSPACES_METEOR_SYNC = 'ACTION_WORKSPACES_METEOR_SYNC';
export const ACTION_WORKSPACES_METEOR_SYNCED = 'ACTION_WORKSPACES_METEOR_SYNCED';

export const BOX_START = 'BOX_START';
export const BOX_START_PROGRESS = 'BOX_START_PROGRESS';
export const BOX_START_DONE = 'BOX_START_DONE';
export const BOX_START_FAIL = 'BOX_START_FAIL';

export const BOX_SHUTDOWN = 'BOX_SHUTDOWN';
export const BOX_SHUTDOWN_PROGRESS = 'BOX_SHUTDOWN_PROGRESS';
export const BOX_SHUTDOWN_DONE = 'BOX_SHUTDOWN_DONE';
export const BOX_SHUTDOWN_FAIL = 'BOX_SHUTDOWN_FAIL';

export const BOX_CREATE = 'BOX_CREATE';
export const BOX_CREATE_PROGRESS = 'BOX_CREATE_PROGRESS';
export const BOX_CREATE_DONE = 'BOX_CREATE_DONE';
export const BOX_CREATE_FAIL = 'BOX_CREATE_FAIL';

export const BOX_REMOVE = 'BOX_REMOVE';
export const BOX_REMOVE_PROGRESS = 'BOX_REMOVE_PROGRESS';
export const BOX_REMOVE_DONE = 'BOX_REMOVE_DONE';
export const BOX_REMOVE_FAIL = 'BOX_REMOVE_FAIL';
