export * as FSEvents from 'fs_events';



export const ACTION_EDITOR_OPEN_FILE = 'ACTION_EDITOR_OPEN_FILE';
export const ACTION_EDITOR_CLOSE_FILE = 'ACTION_EDITOR_CLOSE_FILE';
export const ACTION_EDITOR_TOGGLE_TERM = 'ACTION_EDITOR_TOGGLE_TERM';
export const ACTION_EDITOR_ACTIVATE_TAB = 'ACTION_EDITOR_ACTIVATE_TAB';


export const TARGET_FILE = 'TARGET_FILE';
export const TARGET_DIR = 'TARGET_DIR';

export const JOB_ACTION_RENAME = 'JOB_ACTION_RENAME';
export const JOB_ACTION_CREATION = 'JOB_ACTION_CREATION';
export const JOB_ACTION_REMOVE = 'JOB_ACTION_REMOVE';

export const SHOW_CONTEXT_MODAL = 'SHOW_CONTEXT_MODAL';

export const MODULE_MODAL = 'MODULE_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';


export const ACTION_TERMINAL_INIT = 'ACTION_TERMINAL_INIT';
export const ACTION_TERMINAL_ADD = 'ACTION_TERMINAL_ADD';
export const ACTION_TERMINAL_REMOVE = 'ACTION_TERMINAL_REMOVE';
export const ACTION_TERMINAL_ACTIVATE_TAB = 'ACTION_TERMINAL_ACTIVATE_TAB';
