export const ACTION_SYNC_BOXES = 'ACTION_SYNC_BOXES';

export const ACTION_FS_CAT = 'ACTION_FS_CAT';
export const ACTION_FILE_CHANGE = 'ACTION_FILE_CHANGE';

export const ACTION_SELECT_BOX = 'ACTION_SELECT_BOX';
export const ACTION_LOAD_BOXES = 'ACTION_LOAD_BOXES';

export const ACTION_OPEN_FILE = 'ACTION_OPEN_FILE';
export const ACTION_CLOSE_FILE = 'ACTION_CLOSE_FILE';
export const ACTION_ACTIVATE_TAB = 'ACTION_ACTIVATE_TAB';

export const ACTION_OPEN = 'ACTION_OPEN';

export const ACTION_CREATION = 'ACTION_CREATION';
export const ACTION_REMOVE = 'ACTION_REMOVE';
export const ACTION_DOWNLOAD = 'ACTION_DOWNLOAD';
export const ACTION_RENAME = 'ACTION_RENAME';

export const JOB_READ_BOX_FS = 'JOB_READ_BOX_FS';

export const JOB_ACTION_CREATION = 'JOB_ACTION_CREATION';
export const JOB_ACTION_REMOVE = 'JOB_ACTION_REMOVE';
export const JOB_ACTION_RENAME = 'JOB_ACTION_RENAME';

export const ACTION_TOGGLE_TERMINAL = 'ACTION_TOGGLE_TERMINAL';

export const TARGET_FILE = 'TARGET_FILE';
export const TARGET_DIR = 'TARGET_DIR';

export const STATUS_ACTIVE = 'STATUS_ACTIVE';
export const STATUS_SHUTDOWN = 'STATUS_SHUTDOWN';