export * as FSEvents from 'fs_events';

export const ACTION_SELECT_WORKSPACE = 'ACTION_SELECT_WORKSPACE';

export const ACTION_WORKSPACES_METEOR_SYNC = 'ACTION_WORKSPACES_METEOR_SYNC';

export const ACTION_FS_INIT = 'ACTION_FS_INIT';
export const ACTION_FS_CAT = 'FS_CAT';

export const ACTION_FS_REQUEST_INFO = 'FS_INFO';
export const ACTION_FS_REQUEST_LS = 'FS_LS';
export const ACTION_FS_REQUEST_CAT = 'FS_CAT';
export const ACTION_FS_REQUEST_MKDIR = 'FS_MKDIR';
export const ACTION_FS_REQUEST_TOUCH = 'FS_TOUCH';
export const ACTION_FS_REQUEST_UNLINK = 'FS_UNLINK';
export const ACTION_FS_REQUEST_RENAME = 'FS_RENAME';
export const ACTION_FS_REQUEST_UPDATE = 'FS_UPDATE';

export const ACTION_EDITOR_OPEN_FILE = 'ACTION_EDITOR_OPEN_FILE';
export const ACTION_EDITOR_CLOSE_FILE = 'ACTION_EDITOR_CLOSE_FILE';
export const ACTION_EDITOR_TOGGLE_TERM = 'ACTION_EDITOR_TOGGLE_TERM';
export const ACTION_EDITOR_ACTIVATE_TAB = 'ACTION_EDITOR_ACTIVATE_TAB';

export const WORKSPACE_STATUS_ACTIVE = 'STATUS_ACTIVE';
export const WORKSPACE_STATUS_SHUTDOWN = 'STATUS_SHUTDOWN';

export const EDITOR_JOB_ACTION_CREATION = 'JOB_ACTION_CREATION';
export const EDITOR_JOB_ACTION_REMOVE = 'JOB_ACTION_REOVE';
export const EDITOR_JOB_ACTION_RENAME = 'JOB_ACTION_RENAME';

export const TARGET_FILE = 'TARGET_FILE';
export const TARGET_DIR = 'TARGET_DIR';

export const JOB_ACTION_RENAME = 'JOB_ACTION_RENAME';
export const JOB_ACTION_CREATION = 'JOB_ACTION_CREATION';
export const JOB_ACTION_REMOVE = 'JOB_ACTION_REMOVE';

export const SHOW_CONTEXT_MODAL = 'SHOW_CONTEXT_MODAL';

export const MODULE_MODAL = 'MODULE_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';

